version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec foreman start
    volumes:
      - .:/myapp
    ports:
      - '3000:3000'
      - '3035:3035'
    depends_on:
      - db
