version: '3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=mysecretpassword1234'
    volumes:
      - data:/var/lib/postgresql/data
  web:
    build: .
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec foreman start -f Procfile.dev"
    volumes:
      - .:/myapp
    ports:
      - '3000:3000'
      - '3035:3035'
    depends_on:
      - db
    environment:
      - 'DATABASE_HOST=db'
      - 'DATABASE_PORT=5432'
      - 'DATABASE_USER=postgres'
      - 'DATABASE_PASSWORD=mysecretpassword1234'
volumes:
  data:
