default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 3306 } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'myapp' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>


development:
  <<: *default
   database: myapp_development
   host: 'db'

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
